### ISSUE TITLE
func (*Map) Lookup panic, when value is of the pointer type

### ISSUE THREAD

**Issue by LemmyHuang** [cilium/ebpf#539]
**Describe the bug**
```sh
# Here's panic stack
goroutine 89 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/root/go/pkg/mod/k8s.io/apimachinery@v0.22.3/pkg/util/runtime/runtime.go:55 +0x109
panic(0x16436e0, 0xc00052db90)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
reflect.flag.mustBeAssignableSlow(0x1aa)
	/usr/local/go/src/reflect/value.go:257 +0x1b9
reflect.flag.mustBeAssignable(...)
	/usr/local/go/src/reflect/value.go:247
reflect.Value.SetUint(0x1642f60, 0xc000386340, 0x1aa, 0x0)
	/usr/local/go/src/reflect/value.go:1716 +0x3b
encoding/binary.(*decoder).value(0xc00014f248, 0x1642f60, 0xc000386340, 0x1aa)
	/usr/local/go/src/encoding/binary/binary.go:587 +0xc72
encoding/binary.(*decoder).value(0xc00014f248, 0x17e3480, 0xc000386340, 0x1b9)
	/usr/local/go/src/encoding/binary/binary.go:558 +0x3a8
encoding/binary.(*decoder).value(0xc00014f248, 0x17afe40, 0xc000386340, 0x199)
	/usr/local/go/src/encoding/binary/binary.go:558 +0x3a8
encoding/binary.Read(0x1abeb80, 0xc000725e30, 0x1afe3f8, 0x2541da8, 0x15f27a0, 0xc000386340, 0x46a145, 0xc000502d80)
	/usr/local/go/src/encoding/binary/binary.go:259 +0x33b
github.com/cilium/ebpf.unmarshalBytes(0x15f27a0, 0xc000386340, 0xc000386360, 0x20, 0x20, 0x0, 0x0)
	/root/go/pkg/mod/github.com/cilium/ebpf@v0.7.0/marshalers.go:154 +0x38c
github.com/cilium/ebpf.(*Map).unmarshalValue(0xc000323a40, 0x15f27a0, 0xc000386340, 0xc000386360, 0x20, 0x20, 0x4106d8, 0x20)
	/root/go/pkg/mod/github.com/cilium/ebpf@v0.7.0/map.go:1050 +0x287
github.com/cilium/ebpf.(*Map).Lookup(0xc000323a40, 0x15f2620, 0xc0004286b0, 0x15f27a0, 0xc000386340, 0x10, 0xc0004286b0)
	/root/go/pkg/mod/github.com/cilium/ebpf@v0.7.0/map.go:497 +0xf4
openeuler.io/mesh/pkg/bpf/maps.(*Endpoint).Lookup(0xc0002d732c, 0xc0004286b0, 0xc000005000, 0xc00069266c)
	/root/huanglm/MeshAccelerating/pkg/bpf/maps/endpoint.go:55 +0x85
```

**To Reproduce**
```golang
// Here's my code
type cEndpoint struct {
	entry C.endpoint_t
}

func (ep *Endpoint) Lookup(key *MapKey) error {
	cep := &cEndpoint{}
	err := bpf.Obj.SockConn.ClusterObjects.ClusterMaps.Endpoint.
		Lookup(key, &cep.entry)
	...
	return err
}
```

**Expected behavior**
```golang
// When used like this, it's OK
Lookup(key, cep.entry)
Update(key, &cep.entry, ebpf.UpdateAny)
```

**Comment by lmb** [comment]
I think you omitted the actual panic message, could you add that? It looks to me like the crash is actually from binary.Read, since you're trying to decode into an unexported field. 

> When reading into a struct, all non-blank fields must be exported or Read may panic. 
https://pkg.go.dev/encoding/binary#Read

**Comment by ti-mo** [comment]
> It looks to me like the crash is actually from binary.Read, since you're trying to decode into an unexported field.

That's what it looks like to me, too, but it's likely `C.endpoint_t` that contains the unexported field, which we can't know for sure. Closing this in the meantime, this is not something we can readily fix.
